openapi: 3.0.1
info:
  title: Cloud Gate Consulting Hospital Management System
  description: This is the Authentication microservice.
  contact:
    email: karam.thebian@ieee.org
  version: 1.0.0
servers:
  - url: https://localhost:6004/api/v1
  - url: http://localhost:6004/api/v1

paths:
  /doctor/:
    
    post:
      
      summary: Authorize a doctor
      description: Authorizes a doctor from the databse
      operationId: auth_doctor
      requestBody:
        description: Doctor Credentials
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credentials"
          application/xml:
            schema:
              $ref: "#/components/schemas/Credentials"
        required: true
      responses:
        "200":
          description: JWT token
          content:
            "text/plain":
              schema:
                type: string
        "401":
          description: Incorrect Credentials
          
      x-openapi-router-controller: "openapi_server.controllers.security_controller"
      x-codegen-request-body-name: body
  
  /patient/:
    
    post:
      
      summary: Authorize a patient
      description: Authorizes a patient from the databse
      operationId: auth_patient
      requestBody:
        description: Patient Credentials
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Credentials"
          application/xml:
            schema:
              $ref: "#/components/schemas/Credentials"
        required: true
      responses:
        "200":
          description: JWT token
          content:
            "text/plain":
              schema:
                type: string
        "401":
          description: Incorrect Credentials
          
      x-openapi-router-controller: "openapi_server.controllers.security_controller"
      x-codegen-request-body-name: body

    

components:
  

  schemas:
    Credentials:
      type: object
      properties:
        
        username:
          type: string
        password:
          type: string
        
        
    